import dataclasses


@dataclasses.dataclass(slots=True)
class Tag:
    tags = [
        "a","abbr","address","area","article","aside","audio",
        "b","base","bdi","bdo","blockquote","body","br","button",
        "canvas","caption","cite","code","col","colgroup",
        "data","datalist","dd","del","details","dfn","dialog","div","dl","dt",
        "em", "embed",
        "fieldset","figcaption","figure","footer","form",
        "h1","h2","h3","h4","h5","h6","head","header","hr","html",
        "i","iframe","img","input","ins",
        "kbd",
        "label","legend","li","link",
        "main","map","mark","meta","meter",
        "nav", "noscript",
        "object","ol","optgroup","option","output",
        "p",
        "param","picture","pre","progress",
        "q","rp","rt","ruby",
        "s","samp","script","section","select","small","source","span","strong","style","sub","summary","sup","svg",
        "table","tbody","td","template","textarea","tfoot","th","thead","time","title","tr","track",
        "u", "ul",
        "var","video",
        "wbr"]
    self_closing=['area', 'base', 'br', 'col', 'command', 'embed', 'hr', 'img', 'input', 'keygen', 'link', 'meta', 'param', 'source', 'track', 'wbr']
    nestable   = ['html', 'body', 'head', 'div', 'section', 'article', 'nav', 'aside', 'header', 'footer', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'ul', 'ol', 'li', 'dl', 'dt', 'dd', 'table', 'tr', 'th', 'td', 'caption', 'form', 'fieldset', 'legend', 'label', 'button', 'select', 'optgroup', 'option', 'textarea']
    types      = ["void", "content", "semantic", "structural", "list", "table", "form", "meta"]
    void       = ["area", "base", "br", "col", "command", "embed", "hr", "img", "input", "keygen", "link", "meta", "param", "source", "track", "wbr"]
    content    = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'a', 'img', 'audio', 'video', 'ul', 'ol', 'li', 'table', 'tr', 'td', 'th', 'form', 'input', 'textarea', 'button']
    semantic   = ['article', 'section', 'nav', 'aside', 'header', 'footer', 'main', 'figure', 'figcaption', 'details', 'summary', 'mark', 'time', 'address']
    structural = ['html', 'head', 'title', 'meta', 'body', 'div', 'span', 'br', 'hr']
    embedded   = ['iframe', 'embed', 'object', 'param', 'source']
    list       = ['ul', 'ol', 'li', 'dl', 'dt', 'dd']
    table      = ['table', 'tr', 'td', 'th', 'caption', 'thead', 'tbody', 'tfoot', 'colgroup', 'col']
    form       = ['form', 'input', 'label', 'select', 'option', 'optgroup', 'textarea', 'button', 'datalist', 'fieldset', 'legend', 'output']
    meta       = ['head', 'meta', 'title', 'link', 'style']
    type_lists = [void, content, semantic, structural, embedded, list, table, form, meta] 
    map        = {k:v for k, v in zip(types, type_lists)}
    

  
@dataclasses.dataclass(slots=True)
class Attributes:
    abbr            =       ["class", "id", "style", "title", "aria-label", "aria-labelledby", "aria-describedby"]
    address         =       ["class", "id", "style", "title"]
    area            =       ["alt", "coords", "download", "href", "hreflang", "media", "rel", "shape", "target", "type", "ping", "class", "id", "style", "title"]
    article         =       ["class", "id", "style", "title"]
    aside           =       ["class", "id", "style", "title"]
    audio           =       ["autoplay", "controls", "crossorigin", "loop", "muted", "preload", "src", "class", "id", "style", "title"]
    b               =       ["class", "id", "style", "title"]
    base            =       ["href", "target"]
    bdi             =       ["dir", "class", "id", "style", "title"]
    bdo             =       ["dir", "class", "id", "style", "title"]
    blockquote      =       ["cite", "class", "id", "style", "title"] 
    body            =       ["onafterprint", "onbeforeprint", "onbeforeunload", "onhashchange", "onlanguagechange", "onload", "onmessage", "onmessageerror", "onoffline", "ononline", "onpagehide", "onpageshow", "onpopstate", "onrejectionhandled", "onstorage", "onunhandledrejection", "onunload", "class", "id", "style", "title"]
    br              =       ["class", "id", "style", "title"]
    button          =       ["autofocus", "disabled", "form", "formaction", "formenctype", "formmethod", "formnovalidate", "formtarget", "name", "type", "value", "class", "id", "style", "title"]
    canvas          =       ["width", "height", "class", "id", "style", "title"]
    caption         =       ["align", "class", "id", "style", "title"]
    cite            =       ["class", "id", "style", "title"]
    code            =       ["class", "id", "style", "title"]
    col             =       ["span", "class", "id", "style", "title"]
    colgroup        =       ["span", "class", "id", "style", "title"]
    data            =       ["value", "class", "id", "style", "title"]
    datalist        =       ["class", "id", "style", "title"]
    dd              =       ["class", "id", "style", "title"]
    _del            =       ["cite", "datetime", "class", "id", "style", "title"]
    details         =       ["open", "class", "id", "style", "title"]
    dfn             =       ["class", "id", "style", "title"]
    dialog          =       ["open", "class", "id", "style", "title"]
    div             =       ['id', 'class', 'style', 'title', 'data-']
    dl              =       ["class", "id", "style", "title"]
    dt              =       ["class", "id", "style", "title"]
    em              =       ["class", "id", "style", "title"]
    embed           =       ["src", "type", "width", "height", "class", "id", "style", "title"]
    fieldset        =       ["disabled", "form", "name", "class", "id", "style", "title"]
    figcaption      =       ["class", "id", "style", "title"]
    figure          =       ["class", "id", "style", "title"]
    footer          =       ["class", "id", "style", "title"]
    form            =       ["class", "id", "style", "title"]
    h1              =       ["align", "class", "id", "style", "title"]
    h2              =       ["align", "class", "id", "style", "title"]
    h3              =       ["align", "class", "id", "style", "title"]
    h4              =       ["align", "class", "id", "style", "title"]
    h5              =       ["align", "class", "id", "style", "title"]
    h6              =       ["align", "class", "id", "style", "title"]
    head            =       ["profile", "class", "id", "style", "title"]
    header          =       ["class", "id", "style", "title"]
    hr              =       ["align", "color", "noshade", "size", "width", "class", "id", "style", "title"]
    html            =       ["manifest", "class", "id", "style", "title"]
    i               =       ["accesskey", "class", "contenteditable", "data-*", "dir", "draggable", "hidden", "id", "lang", "style", "tabindex", "title", "translate"]
    iframe          =       ["allow", "allowfullscreen", "allowpaymentrequest", "allowtransparency", "class", "loading", "sandbox", "src", "srcdoc", "style", "title"]
    img             =       ["alt", "border", "class", "crossorigin", "decoding", "height", "importance", "intrinsicsize", "ismap", "loading", "referrerpolicy", "sizes", "src", "srcset", "style", "title", "usemap", "width"]
    input           =       ["accept", "accesskey", "alt", "autocomplete", "autofocus", "capture", "checked", "class", "contenteditable", "dir", "dirname", "disabled", "form", "formaction", "formenctype", "formmethod", "formnovalidate", "formtarget", "height", "hidden", "id", "inputmode", "ismap", "lang", "list", "max", "maxlength", "min", "minlength", "multiple", "name", "pattern", "placeholder", "readonly", "required", "size", "spellcheck", "src", "step", "style", "tabindex", "title", "translate", "type", "usemap", "value", "width"]
    ins             =       ["cite", "class", "datetime", "style", "title"]
    kbd             =       ["class", "contenteditable", "data-*", "dir", "hidden", "id", "lang", "style", "tabindex", "title", "translate"]
    label           =       ["accesskey", "class", "contenteditable", "for", "form", "hidden", "id", "lang", "style", "tabindex", "title", "translate"]
    legend          =       ["accesskey", "align", "class", "contenteditable", "dir", "hidden", "id", "lang", "style", "tabindex", "title", "translate"]
    li              =       ["accesskey", "class", "contenteditable", "dir", "hidden", "id", "lang", "style", "tabindex", "title", "translate", "type", "value"]
    link_attributes =       ['href', 'hreflang', 'media', 'rel', 'sizes', 'type']
    main            =       []
    map             =       ['name']
    mark            =       []
    meta            =       ['charset', 'content', 'http-equiv', 'name']
    meter           =       ['form', 'high', 'low', 'max', 'min', 'optimum', 'value']
    nav             =       []
    noscript        =       []
    object          =       ['data', 'form', 'height', 'name', 'type', 'usemap', 'width']
    ol              =       ['reversed', 'start', 'type']
    optgroup        =       ['disabled', 'label']
    option          =       ['disabled', 'label', 'selected', 'value']
    output          =       ['for', 'form', 'name']
    p               =       []
    param           =       ['name', 'type', 'value', 'valuetype']
    picture         =       []
    pre             =       []
    progress        =       ['max', 'value']
    q               =       ['cite']
    rp              =       []
    rt              =       []
    ruby            =       []
    s               =       ['accesskey', 'class', 'contenteditable', 'dir', 'draggable', 'hidden', 'id', 'lang', 'spellcheck', 'style', 'tabindex', 'title', 'translate']
    samp            =       ['accesskey', 'class', 'contenteditable', 'dir', 'draggable', 'hidden', 'id', 'lang', 'spellcheck', 'style', 'tabindex', 'title', 'translate']
    script          =       ['async', 'charset', 'class', 'defer', 'integrity', 'language', 'src', 'type']
    section         =       ['accesskey', 'class', 'contenteditable', 'dir', 'draggable', 'hidden', 'id', 'lang', 'spellcheck', 'style', 'tabindex', 'title', 'translate']
    select          =       ['accesskey', 'autofocus', 'class', 'contenteditable', 'dir', 'disabled', 'form', 'hidden', 'id', 'lang', 'multiple', 'name', 'required', 'size', 'spellcheck', 'style', 'tabindex', 'title', 'translate']
    small           =       ['accesskey', 'class', 'contenteditable', 'dir', 'draggable', 'hidden', 'id', 'lang', 'spellcheck', 'style', 'tabindex', 'title', 'translate']
    source          =       ['media', 'sizes', 'src', 'srcset', 'type']
    span            =       ['accesskey', 'class', 'contenteditable', 'dir', 'draggable', 'hidden', 'id', 'lang', 'spellcheck', 'style', 'tabindex', 'title', 'translate']
    strong          =       ['accesskey', 'class', 'contenteditable', 'dir', 'draggable', 'hidden', 'id', 'lang', 'spellcheck', 'style', 'tabindex', 'title', 'translate']
    style           =       ['media', 'scoped', 'type']
    sub             =       ['accesskey', 'class', 'contenteditable', 'dir', 'draggable', 'hidden', 'id', 'lang', 'spellcheck', 'style', 'tabindex', 'title', 'translate']
    summary         =       ['accesskey', 'class', 'contenteditable', 'dir', 'draggable', 'hidden', 'id', 'lang', 'spellcheck', 'style', 'tabindex', 'title', 'translate']
    sup             =       ['accesskey', 'class', 'contenteditable', 'dir', 'draggable', 'hidden', 'id', 'lang', 'spellcheck', 'style', 'tabindex', 'title', 'translate']
    svg             =       ['class', 'height', 'id', 'style', 'viewBox', 'width', 'xmlns']
    table           =       ['align', 'bgcolor', 'border', 'cellpadding', 'cellspacing', 'class', 'dir', 'frame', 'height', 'id', 'lang', 'rules', 'style', 'summary', 'width']
    tbody           =       ['align', 'bgcolor', 'char', 'charoff', 'valign']
    td              =       ['abbr', 'align', 'axis', 'bgcolor', 'char', 'charoff', 'colspan', 'headers', 'height', 'nowrap', 'rowspan', 'scope', 'valign', 'width']
    template        =       ['content', 'id']
    textarea        =       ['autocomplete', 'autofocus', 'cols', 'dirname', 'disabled', 'form', 'maxlength', 'minlength', 'name', 'placeholder', 'readonly', 'required', 'rows', 'wrap']
    tfoot           =       ['align', 'bgcolor', 'char', 'charoff', 'valign']
    th              =       ['abbr', 'align', 'axis', 'bgcolor', 'char', 'charoff', 'colspan', 'headers', 'height', 'nowrap', 'rowspan', 'scope', 'valign', 'width']
    thead           =       ['align', 'bgcolor', 'char', 'charoff', 'valign']
    time            =       ['datetime']
    title           =       []
    tr              =       ['align', 'bgcolor', 'char', 'charoff', 'valign']
    track           =       ['default', 'kind', 'label', 'src', 'srclang']
    u               =       []
    ul              =       ['type']
    var             =       []
    video           =       ['autoplay', 'controls', 'crossorigin', 'height', 'loop', 'muted', 'playsinline', 'poster', 'preload', 'src', 'width']
    wbr             =       []
    all             =       [abbr, address, area, article, aside, audio, b, base, bdi, bdo, blockquote, body, br, button, canvas, caption, cite, code, col, colgroup, data, datalist, dd, _del, details, dfn, dialog, div, dl, dt, em, embed, fieldset, figcaption, figure, footer, form, h1, h2, h3, h4, h5, h6, head, header, hr, html, i, iframe, img, input, ins, kbd, label, legend, li, link_attributes, main, map, mark, meta, meter, nav, noscript, object, ol, optgroup, option, output, p, param, picture, pre, progress, q, rp, rt, ruby, s, samp, script, section, select, small, source, span, strong, style, sub, summary, sup, svg, table, tbody, td, template, textarea, tfoot, th, thead, time, title, tr, track, u, ul, var, video, wbr]
    map             =       {k:v for k, v in zip(Tag.tags, all)}
    map["wbr"] = wbr


@dataclasses.dataclass(slots=True)
class TagType:
    a = ['content']
    abbr = []
    address = ['semantic']      
    area = ['void']
    article = ['semantic']      
    aside = ['semantic']        
    audio = ['content']
    b = []
    base = ['void']
    bdi = []
    bdo = []
    blockquote = []
    body = ['structural']       
    br = ['void', 'structural'] 
    button = ['content', 'meta']
    canvas = []
    caption = ['form']
    cite = []
    code = []
    col = ['void', 'form']
    colgroup = ['form']
    data = []
    datalist = ['meta']
    dd = ['table']
    _del = []
    details = ['semantic']
    dfn = []
    dialog = []
    div = ['structural']
    dl = ['table']
    dt = ['table']
    em = []
    embed = ['void', 'list']
    fieldset = ['meta']
    figcaption = ['semantic']
    figure = ['semantic']
    footer = ['semantic']
    form = ['content', 'meta']
    h1 = ['content']
    h2 = ['content']
    h3 = ['content']
    h4 = ['content']
    h5 = ['content']
    h6 = ['content']
    head = ['structural']
    header = ['semantic']
    hr = ['void', 'structural']
    html = ['structural']
    i = []
    iframe = ['list']
    img = ['void', 'content']
    input = ['void', 'content', 'meta']
    ins = []
    kbd = []
    label = ['meta']
    legend = ['meta']
    li = ['content', 'table']
    link = ['void']
    main = ['semantic']
    map = []
    mark = ['semantic']
    meta = ['void', 'structural']
    meter = []
    nav = ['semantic']
    noscript = []
    object = ['list']
    ol = ['content', 'table']
    optgroup = ['meta']
    option = ['meta']
    output = ['meta']
    p = ['content']
    param = ['void', 'list']
    picture = []
    pre = []
    progress = []
    q = []
    rp = []
    rt = []
    ruby = []
    s = []
    samp = []
    script = []
    section = ['semantic']
    select = ['meta']
    small = []
    source = ['void', 'list']
    span = ['structural']
    strong = []
    style = []
    sub = []
    summary = ['semantic']
    sup = []
    svg = []
    table = ['content', 'form']
    tbody = ['form']
    td = ['content', 'form']
    template = []
    textarea = ['content', 'meta']
    tfoot = ['form']
    th = ['content', 'form']
    thead = ['form']
    time = ['semantic']
    title = ['structural']
    tr = ['content', 'form']
    track = ['void']
    u = []
    ul = ['content', 'table']
    var = []
    video = ['content']
    wbr = ['void']